
import javax.swing.*;
import java.util.ArrayList;
import java.util.Observer;
import java.util.Observable;

/**
 *
 * @author ana
 */
public class Analista extends javax.swing.JFrame implements Observer {

    //Mostrará las ventas de los últimos 7 días
    
    public ArrayList<Integer> ventasDia;
    public ArrayList<Integer> ventasTotales;
    
    // Para controlar los dias
    private int contador;
    private int dia_semana;
    private int suma;
    
    private double precioCestas;
    private double precioPan;
    
    private int nSimples;
    private int nCompuestos;
    private int simplesVendidos;
    private int compuestosVendidos;
    
    public String mensajeSimples;
    public String mensajeCompuestos;
    
    
    /**
     * Creates new form Analista_panel
     */
    public Analista() {
        ventasDia = new ArrayList<>();
        ventasTotales = new ArrayList<>();
        
        for(int i=0; i<7; i++){
            ventasTotales.add(0);
            System.out.println("size: " + ventasTotales.size());
        }
        
        
        contador = 0;
        dia_semana = 0;
        suma = 0;

        nSimples = 0;
        nCompuestos = 0;
        simplesVendidos = 0;
        compuestosVendidos = 0;
        mensajeSimples = "";
        mensajeCompuestos = "";
        
        initComponents();
              
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lunes = new java.awt.Label();
        martes = new java.awt.Label();
        miercoles = new java.awt.Label();
        jueves = new java.awt.Label();
        viernes = new java.awt.Label();
        sabado = new java.awt.Label();
        domingo = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lunes.setText(Integer.toString(ventasTotales.get(0)));

        martes.setText(Integer.toString(ventasTotales.get(1)));

        miercoles.setText(Integer.toString(ventasTotales.get(2)));

        jueves.setText(Integer.toString(ventasTotales.get(3)));

        viernes.setText(Integer.toString(ventasTotales.get(4)));

        sabado.setText(Integer.toString(ventasTotales.get(5)));

        domingo.setText(Integer.toString(ventasTotales.get(6)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(martes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(domingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(domingo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sabado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viernes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jueves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(miercoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(martes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Analista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Analista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Analista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Analista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Analista().setVisible(true);
            }
        });
    }
    
    @Override
    public void update(Observable o, Object arg){
        //Se le avisa de los productos disponibles en la tienda y los que ya se han vendido
        try {
            Thread.sleep(500);
        } catch (InterruptedException ex){

        }
        
        Panaderia panaderia = (Panaderia) o;
        suma = 0; // sera las ventas de un dia
        int vendidos = (nSimples+nCompuestos) - ( panaderia.getNSimples()+panaderia.getNCompuestos() );
        System.out.println("--------VENDIDOS: "+ vendidos); // para ver si recibe bien la cantidad de vendidos
        
        if(contador == 0){ // inicializar la panaderia, para saber cuantos productos hay inicialmente
            contador++;
        }
        else if(contador == 4){ // cambio de dia
            contador = 1;

            // Suma de todas las ventas en el mismo dia
            for(int i=0; i<3; i++){
                suma += ventasDia.get(i);
                System.out.println("suma: "+suma+" ventasDia.get("+i+"):" + ventasDia.get(i));
            }
            
            ventasTotales.set(dia_semana, suma);
            
            System.out.println("--->Dia semana: " + dia_semana + " con ventas: " + suma + ". Contador: " + contador);
            
            // actualizar el texto del panel cuando se sepa las ventas del dia
            switch(dia_semana){
                case 0:
                    lunes.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
                case 1:
                    martes.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
                case 2:
                    miercoles.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
                case 3:
                    jueves.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
                case 4:
                    viernes.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
                case 5:
                    sabado.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
                case 6:
                    domingo.setText(Integer.toString(ventasTotales.get(dia_semana)));
                break;
            }
            
            dia_semana++; // cambiamos de dia
            
            ventasDia.clear();
            ventasDia.add(vendidos); // añade esa venta a la venta del proximo dias
            
        } 
        else{ // sigue vendiendo en el mismo dia
            System.out.println("--->Dia semana: " + dia_semana + ". Contador : " + contador);
            ventasDia.add(vendidos);
            contador++;
        }
         
       
        nSimples = panaderia.getNSimples();
        nCompuestos = panaderia.getNCompuestos();
        simplesVendidos = panaderia.getSimplesVendidos();
        compuestosVendidos = panaderia.getCompuestosVendidos();

        
        mensajeSimples = "El número de productos simples en stock es " + nSimples + " y ya se han vendido " + simplesVendidos;
        mensajeCompuestos = "El número de productos compuestos en stock es " + nCompuestos + " y ya se han vendido " + compuestosVendidos;

    }
    
    public String getStock(){
        return ("Analista --> " + mensajeSimples + mensajeCompuestos);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Label domingo;
    private java.awt.Label jueves;
    private java.awt.Label lunes;
    private java.awt.Label martes;
    private java.awt.Label miercoles;
    private java.awt.Label sabado;
    private java.awt.Label viernes;
    // End of variables declaration//GEN-END:variables
}
