/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Beans/Customizer.java to edit this template
 */

/**
 *
 * @author ana
 */
public class Cliente_prueba extends javax.swing.JPanel implements java.beans.Customizer {
    
    private int nSimples = 20;
    private int nCompuestos = 30;
    
    private Object bean;

    /**
     * Creates new customizer Cliente_prueba
     */
    public Cliente_prueba() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simples = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        variable = new java.awt.Label();

        setLayout(new java.awt.BorderLayout());

        variable.setText("variable: "+ nSimples);
        jPanel1.add(variable);

        simples.add(jPanel1);

        add(simples, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel simples;
    private java.awt.Label variable;
    // End of variables declaration//GEN-END:variables
}
